export * from "./homeSuperAdminCona"
export * from "./graficasSuperAdminCona"
export * from "./pacientesSuperAdminCona"
export * from "./gestoresSuperAdminCona"
export * from "./noticiasSuperAdminCona"